---
services:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible and molecule
  - pip install ansible-lint molecule docker

script:
  - molecule test --scenario-name travis

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
