---
services:
  - docker

# Install python3 and pip
addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools

install:
  # Install ansible and molecule
  - pip3 install ansible-lint molecule docker

script:
  - molecule test --scenario-name travis

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
